### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by galinawind** [hobu/nitro#9]
Greetings!

I am trying to build Nitro and the instructions fail immediately: 
```
python` ./waf configure build
 can't open file './build/waf': [Errno 2] No such file or directory
```
The directory build/ does not exist in the package one downloads, so I don't know how to get around this. Thank you very much.

**Comment by Miakonn** [comment]
I have the same problem. I downloaded the source and installed python. I then entered
````
python waf configure --enable-debugging --prefix=installed
 can't open file './build/waf': [Errno 2] No such file or directory
````
I tested creating the build directory and downloading WAF:
````
mkdir build
curl -o build/waf https://waf.io/waf-2.0.15
````
Now at least I got WAF to call.

I tested again
````
python waf configure --enable-debugging --prefix=installed
Traceback (most recent call last):
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Scripting.py", line 178, in run_commands
    parse_options()
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Scripting.py", line 158, in parse_options
    ctx.execute()
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Options.py", line 198, in execute
    super(OptionsContext,self).execute()
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Context.py", line 85, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Context.py", line 126, in recurse
    user_function(self)
  File "C:\Repos\nitro-master\wscript", line 15, in options
    opt.load(TOOLS + ' msvs dumpenv', tooldir='build')
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Context.py", line 80, in load
    module=load_tool(t,path,with_sys_path=with_sys_path)
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Context.py", line 373, in load_tool
    __import__(tool)
ImportError: No module named 'build'
````

So, I am not sure I am on the right track. 

I am running Windows 10 and hoping to get it to work in Visual Studio 2017.

Please, can anyone help us!

**Comment by hobu** [comment]
This repository is a fork of https://github.com/mdaus/nitro and exists mostly for CMake support. Jump over there and you should get going.
